version: '3'

services:
  api:
    container_name: api
    ports:
      - 8000:8000
      - 5002:5002
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    environment:
      - GOPATH=/go
    volumes:
      # ホストOS：コンテナ側
      - ./:/go/src/github.com/birnamwood/go-server-base/